/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Configuration for opening a Settle instance. */
export interface SettleConfig {
  /** SQL schema definition string. */
  schema: string
  /**
   * Path to RocksDB data directory for persistence.
   * When omitted, uses in-memory storage (data lost on restart).
   */
  dataDir?: string
  /** Maximum buffer size before backpressure (default: 10000). */
  maxBufferSize?: number
  /** Compression algorithm for RocksDB: "none", "snappy" (default), "zstd", "lz4". */
  compression?: string
  /** Disable RocksDB automatic background compactions. */
  disableCompaction?: boolean
  /**
   * Block cache size in bytes. Omit for RocksDB default (~8MB per CF), 0 to disable.
   * Capped at the target's `usize::MAX` (≈18 EB on 64-bit, ≈4 GB on 32-bit);
   * values above that are rejected. JS `number` precision is exact only up to
   * `2^53` (≈9 PB), so larger values cannot be passed reliably from JS anyway.
   * Negative values are rejected.
   */
  cacheSize?: number
}
/** Block cursor: number + hash. */
export interface SettleCursor {
  number: number
  hash: string
}
/** Result of `handleFork()`. */
export interface ForkResultJs {
  /** The block to resume ingestion from (highest common ancestor). */
  cursor: SettleCursor
  /** Compensating change batch (msgpack-encoded), or null if nothing was rolled back. */
  batch?: Buffer
}
/** Input for the atomic `ingest()` method. */
export interface IngestInput {
  /** Table name → rows, msgpack-encoded as `{tableName: [{col: val}, ...], ...}`. */
  data: Buffer
  /** Unfinalized blocks with hashes for fork resolution. */
  rollbackChain?: Array<SettleCursor>
  /** Finalized head cursor — both number and hash stored. */
  finalizedHead: SettleCursor
}
/** State field definition for external reducers. */
export interface ExternalStateField {
  name: string
  /** Column type: "Float64", "UInt64", "Int64", "String", "Boolean", "Json" */
  columnType: string
  /** Default value as a string literal (e.g., "0", "'hello'", "{}") */
  defaultValue: string
}
/** Configuration for registering an external reducer. */
export interface ExternalReducerConfig {
  name: string
  source: string
  groupBy: Array<string>
  state: Array<ExternalStateField>
}
/** Settle N-API wrapper. */
export declare class Settle {
  /** Open a new Settle instance. */
  static open(config: SettleConfig): Settle
  /**
   * Register a brand-new external reducer + JS batch callback.
   *
   * **Strict semantics**: errors if a reducer with this name already
   * exists (whether declared in SQL via `LANGUAGE EXTERNAL` or registered
   * via a prior call). To attach a callback to a reducer that was
   * declared in SQL, use `registerReducerCallback(name, callback)`.
   * To change a callback after it's registered, drop and reopen the
   * instance — silent hot-reload is not supported.
   *
   * The callback receives an array of `{ state, rows }` groups and must
   * return an array of `{ state, emits }` results (same length, same order).
   */
  registerReducer(config: ExternalReducerConfig, callback: (...args: any[]) => any): void
  /**
   * Attach a JS callback to an existing reducer that was declared in
   * SQL with `LANGUAGE EXTERNAL`, and re-replay unfinalized blocks
   * through it.
   *
   * **Strict semantics**: errors if no reducer named `name` exists,
   * AND errors if a callback is already registered for that name. To
   * change a registered callback, drop and reopen the instance.
   */
  registerReducerCallback(name: string, callback: (...args: any[]) => any): void
  /**
   * Process a batch of rows for a raw table.
   * Atomic ingest: process all tables, store rollback chain, finalize, flush.
   * Returns a msgpack-encoded ChangeBatch buffer, or null if no records produced.
   */
  ingest(input: IngestInput): Buffer | null
  /**
   * Find the common ancestor between our state and the Portal's chain.
   * Returns the matching block cursor, or null if no common ancestor found.
   */
  resolveForkCursor(previousBlocks: Array<SettleCursor>): SettleCursor | null
  /**
   * Atomically handle a fork (409 from Portal).
   *
   * Finds the common ancestor in `previousBlocks`, rolls back all state after
   * that point, and returns the cursor to resume from plus any compensating
   * change batch (msgpack-encoded). Uses the internal finalized block — no need
   * to pass it in.
   *
   * Throws if no common ancestor is found (fork too deep / unrecoverable).
   */
  handleFork(previousBlocks: Array<SettleCursor>): ForkResultJs
  /**
   * Acknowledge the pending batch by sequence number and durably commit
   * its writes. `sequence` is passed as `i64` — the JS-side accepts a
   * non-negative integer up to `Number.MAX_SAFE_INTEGER` (2^53), well
   * below `i64::MAX`; the TS wrapper rejects fractional / out-of-range
   * values before they reach this boundary.
   *
   * Returns the typed errors `SettlePendingAckError` / `SettleWrongAckSequenceError`
   * via the structured-reason prefix protocol; the TS wrapper rethrows them
   * as typed classes.
   */
  ack(sequence: number): void
  /**
   * Number of pending (unflushed) change records in the buffer. Does NOT
   * reflect the pending-ack slot — see `isAwaitingAck` for that.
   */
  get pendingCount(): number
  /** Whether backpressure should be applied. */
  get isBackpressured(): boolean
  /**
   * Whether a previously-returned `ChangeBatch` is still awaiting `ack()`.
   * While true, mutating APIs (`ingest`, `handleFork`, `registerReducer`)
   * throw `SettlePendingAckError`.
   */
  get isAwaitingAck(): boolean
  /**
   * Whether an unrecoverable commit failure has poisoned this instance.
   * Once true the only recovery is to drop the instance and reopen — all
   * mutating calls reject with `Error("instance poisoned ...")` so the
   * caller does not silently produce stale writes.
   */
  get isPoisoned(): boolean
  /** Current cursor: latest processed block + hash. Null if no blocks processed. */
  get cursor(): SettleCursor | null
}
